pipeline {
    agent any

    parameters {
        string(
            name: 'TARGET_PROJECT',
            defaultValue: 'libjpeg-turbo',
            description: 'OSS-Fuzz project name'
        )

        choice(
            name: 'TARGET_SANITIZER',
            choices: ['address', 'undefined', 'memory', 'thread'],
            description: 'OSS-Fuzz sanitizer for normal builds'
        )

        choice(
            name: 'TARGET_ENGINE',
            choices: ['libfuzzer', 'afl', 'honggfuzz'],
            description: 'OSS-Fuzz engine for normal builds'
        )

        string(
            name: 'TARGET_ARCH',
            defaultValue: 'x86_64',
            description: 'OSS-Fuzz architecture'
        )

        booleanParam(
            name: 'ENABLE_SYMSAN',
            defaultValue: false,
            description: 'Enable SymSan hybrid fuzzing. Builds normal AFL++ + SymSan symbolic binaries.'
        )
    }

    environment {
        OSS_FUZZ_REPO = 'https://github.com/google/oss-fuzz.git'
        SYMSAN_REPO = 'https://github.com/R-Fuzz/symsan.git'
        AFLPP_REPO = 'https://github.com/AFLplusplus/AFLplusplus.git'

        LLVM_VERSION = '18'
        REMOTE_HOST = '192.168.18.56'
        REMOTE_USER = 'ubuntu24'
        REMOTE_PASS = 'admin'
        SYMSAN_IMAGE = "oss-fuzz-symsan-${BUILD_NUMBER}"
        SYMSAN_HOME = '/opt/symsan'
        AFLPP_HOME = '/opt/aflpp'
    }

    stages {
        stage('Set Build Name') {
            steps {
                script {
                    if (params.ENABLE_SYMSAN) {
                        currentBuild.displayName = "${params.TARGET_PROJECT}_symsan_aflpp_llvm18"
                    } else {
                        currentBuild.displayName = "${params.TARGET_PROJECT}_${params.TARGET_ENGINE}_${params.TARGET_SANITIZER}"
                    }
                }
            }
        }

        stage('Setup OSS-Fuzz Environment') {
            steps {
                sh "bash '${WORKSPACE}/PipelineScripts/setup_oss_fuzz.sh' '${OSS_FUZZ_REPO}' '${WORKSPACE}/oss-fuzz'"
            }
        }

        stage('Build OSS-Fuzz Base Image') {
            steps {
                sh "bash '${WORKSPACE}/PipelineScripts/build_oss_fuzz_base_image.sh' '${params.TARGET_PROJECT}' '${params.TARGET_ARCH}'"
            }
        }

        stage('Prepare SymSan + AFL++ LLVM 18 Image') {
            when {
                expression {
                    return params.ENABLE_SYMSAN
                }
            }

            steps {
                sh "bash '${WORKSPACE}/PipelineScripts/prepare_symsan_image.sh'"
            }
        }

        stage('Compile Normal Fuzz Targets') {
            when {
                expression {
                    return !params.ENABLE_SYMSAN
                }
            }

            steps {
                sh "bash '${WORKSPACE}/PipelineScripts/build_normal_fuzz_targets.sh' '${params.TARGET_PROJECT}' '${params.TARGET_ENGINE}' '${params.TARGET_SANITIZER}' '${params.TARGET_ARCH}'"
            }
        }

        stage('SymSan - Build AFL++ Fuzzing Binary') {
            when {
                expression {
                    return params.ENABLE_SYMSAN
                }
            }

            steps {
                sh "bash '${WORKSPACE}/PipelineScripts/build_afl_binary.sh' '${params.TARGET_PROJECT}' '${params.TARGET_ARCH}'"
            }
        }

        stage('SymSan - Build Symbolic Binary') {
            when {
                expression {
                    return params.ENABLE_SYMSAN
                }
            }

            steps {
                sh "bash '${WORKSPACE}/PipelineScripts/build_symsan_binary.sh' '${params.TARGET_PROJECT}' '${params.TARGET_ARCH}'"
            }
        }

        stage('Prepare SymSan Runtime Bundle') {
            when {
                expression {
                    return params.ENABLE_SYMSAN
                }
            }

            steps {
                sh "bash '${WORKSPACE}/PipelineScripts/prepare_symsan_runtime_bundle.sh' 'oss-fuzz/build/out/${params.TARGET_PROJECT}'"
            }
        }

        stage('Verify Build') {
            steps {
                sh "bash '${WORKSPACE}/PipelineScripts/verify_build.sh' 'oss-fuzz/build/out/${params.TARGET_PROJECT}'"
            }
        }

        stage('Upload Build to Remote Server') {
            steps {
                sh "bash '${WORKSPACE}/PipelineScripts/upload_build.sh'"
            }
        }
    }

    post {
        always {
            archiveArtifacts(
                artifacts: 'oss-fuzz/build/out/**/*',
                allowEmptyArchive: true
            )

            cleanWs()
        }
    }
}
